version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3.7.5-management
    container_name: rabbitmq-container
    network_mode: "host"
    hostname: localhost
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST:
    ports:
      - 5672:5672
      - 15672:15672

  mongodbservice:
    image: mongo:latest
    container_name: mongo-container
    network_mode: host
    hostname: localhost
    ports:
      - 27017:27017

  soulmate-service:
    container_name: soulmate-service
    build: soulmate-service/
    hostname: localhost
    network_mode: host
    ports:
      - 8088:8088
    depends_on:
      - mongodbservice
    restart: always


















